plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ru.nsu.bukhanov'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]
}
test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}
def excludeFromCoverage = [
        'ru/nsu/bukhanov/snake/Main.class',
        'ru/nsu/bukhanov/snake/controller/**',
        'ru/nsu/bukhanov/snake/view/**'
]
jacocoTestReport {
    dependsOn test
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: excludeFromCoverage)
        }))
    }
    reports {
        xml.required = true
        html.required = true
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: excludeFromCoverage)
        }))
    }
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification

application {
    mainClass = 'ru.nsu.bukhanov.snake.Main'
}

tasks.named('run') {
    standardInput = System.in
}